<?php

/**
 * @file
 * Hook implementations for the MailerSend module.
 */

/**
 * Implements hook_theme().
 */
function mailersend_theme() {
  return [
    'mailersend_message' => [
      'variables' => [
        'module' => NULL,
        'key' => NULL,
        'subject' => NULL,
        'body' => NULL,
        'site_name' => NULL,
        'langcode' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_mailersend_message(array &$variables) {
  $variables['module'] = str_replace('_', '-', $variables['module']);
  $variables['key'] = str_replace('_', '-', $variables['key']);
}

/**
 * Inspired by mimemail module.
 *
 * Implements hook_theme_suggestions_HOOK().
 *
 * @see https://git.drupalcode.org/project/mimemail/-/blob/8.x-1.x/mimemail.module
 */
function mimemail_theme_suggestions_mimemail_message(array $variables) {
  return [
    'mailersend_message__' . $variables['module'],
    'mailersend_message__' . $variables['module'] . '__' . $variables['key'],
  ];
}
