mailersend.settings:
  type: config_object
  mapping:
    api_key:
      type: string
      label: 'API key'
    queue:
      type: boolean
      label: 'Queue'
    html:
      type: boolean
      label: 'HTML'
    html_format:
      type: string
      label: 'HTML Format'
    email:
      type: string
      label: 'From Address'
    analytics:
      type: mapping
      label: 'Analytics options'
      mapping:
        opens:
          type: boolean
          label: 'Track opens'
        clicks:
          type: boolean
          label: 'Track clicks'
        content:
          type: boolean
          label: 'Track content'
